version: '2'
services:
  db:
    build: Database
    environment:
      - POSTGRES_USER="pokindex"
      - POSTGRES_PASSWORD="pokindex"
      - PGDATA="/var/lib/postgresql/data"
      - POSTGRES_INITDB_ARGS="--data-checksums"

  grafana:
    image: kamon/grafana_graphite
    ports:
      - 8000:80
      - 8100:81
      - 8125:8125/udp
      - 8126:8126

  back:
    build: pokeserver
    volumes:
      - ./pokeserver/App/:/home/pokeserver/
    depends_on:
      - db

  front:
    build: pokindex
    volumes:
      - ./pokindex/App/:/home/pokindex/
    ports:
      - 3000:3000
    depends_on:
      - db
      - back